version: "3"

services:
  server:
    build: .
    ports:
      - "3000:3000"
    networks:
      - no-internet
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - web
      - no-internet

  # certbot:
  #   image: certbot/certbot
networks:
  web:
    driver: bridge
  no-internet:
    driver: bridge
    internal: true # Block internet access
